import { describe, expect, test } from "bun:test";
import type { JiraTicket } from "../jira/jiraTicket.ts";
import { buildHtml } from "./buildHtml.ts";

const baseTicket: JiraTicket = {
  key: "PROJ-1",
  summary: "Fix the login bug",
  status: "Done",
  issueType: "Bug",
  priority: "High",
  assignee: "John Doe",
  reporter: "Jane Smith",
  sprint: "Sprint 10",
  labels: [],
  fixVersions: [],
  resolutionDate: "2024-01-15",
  created: "2024-01-10",
  updated: "2024-01-15",
  description: "",
  url: "https://jira.example.com/browse/PROJ-1",
};

const PR_URL = "https://github.com/owner/repo/pull/42";

describe("buildHtml", () => {
  test("returns a complete HTML document", () => {
    const html = buildHtml([baseTicket], PR_URL);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("</html>");
  });

  test("links each ticket key to its Jira URL", () => {
    const html = buildHtml([baseTicket], PR_URL);
    expect(html).toContain(`<a href="${baseTicket.url}">${baseTicket.key}</a>`);
  });

  test("includes the ticket summary", () => {
    const html = buildHtml([baseTicket], PR_URL);
    expect(html).toContain(baseTicket.summary);
  });

  test("links the PR button to the given PR URL", () => {
    const html = buildHtml([baseTicket], PR_URL);
    expect(html).toContain(`href="${PR_URL}"`);
  });

  test("shows the correct ticket count in the intro line", () => {
    const html = buildHtml([baseTicket, { ...baseTicket, key: "PROJ-2" }], PR_URL);
    expect(html).toContain("2 ticket(s)");
  });

  test("renders a table row for each ticket", () => {
    const html = buildHtml([baseTicket, { ...baseTicket, key: "PROJ-2" }], PR_URL);
    expect(html).toContain("PROJ-1");
    expect(html).toContain("PROJ-2");
  });

  test("includes the auto-generated footer", () => {
    const html = buildHtml([baseTicket], PR_URL);
    expect(html).toContain("Auto-generated by TicketSync");
  });

  test("includes assignee and priority columns in table header", () => {
    const html = buildHtml([baseTicket], PR_URL);
    expect(html).toContain("<th>Assignee</th>");
    expect(html).toContain("<th>Priority</th>");
  });
});
