import { format } from "date-fns";
import type { JiraTicket } from "../jira/jiraTicket.ts";

export function buildPrBody(tickets: JiraTicket[]): string {
  const rows = tickets
    .map(
      (t) =>
        `| [${t.key}](${t.url}) | ${t.summary} | ${t.issueType} | ${t.priority} | ${t.assignee} | ${t.resolutionDate} |`
    )
    .join("\n");

  return `## Tickets Moved to Done

| Key | Summary | Type | Priority | Assignee | Resolution Date |
|-----|---------|------|----------|----------|-----------------|
${rows}

---
*Auto-generated by TicketSync on ${format(new Date(), "PPpp")}*`;
}
