import { describe, expect, test } from "bun:test";
import type { JiraTicket } from "../jira/jira-ticket.ts";
import { buildPrBody } from "./build-pr-body.ts";

const baseTicket: JiraTicket = {
  key: "PROJ-1",
  summary: "Fix the login bug",
  status: "Done",
  issueType: "Bug",
  priority: "High",
  assignee: "John Doe",
  reporter: "Jane Smith",
  sprint: "Sprint 10",
  labels: [],
  fixVersions: [],
  resolutionDate: "2024-01-15",
  created: "2024-01-10",
  updated: "2024-01-15",
  description: "",
  url: "https://jira.example.com/browse/PROJ-1",
};

describe("buildPrBody", () => {
  test("includes the section heading", () => {
    const body = buildPrBody([baseTicket]);
    expect(body).toContain("## Tickets Moved to Done");
  });

  test("includes the markdown table header row", () => {
    const body = buildPrBody([baseTicket]);
    expect(body).toContain("| Key | Summary | Type | Priority | Assignee | Resolution Date |");
  });

  test("renders a markdown link for the ticket key", () => {
    const body = buildPrBody([baseTicket]);
    expect(body).toContain(`[${baseTicket.key}](${baseTicket.url})`);
  });

  test("includes the ticket summary, assignee and resolution date in the row", () => {
    const body = buildPrBody([baseTicket]);
    expect(body).toContain(baseTicket.summary);
    expect(body).toContain(baseTicket.assignee);
    expect(body).toContain(baseTicket.resolutionDate);
  });

  test("renders a row for every ticket", () => {
    const ticket2 = {
      ...baseTicket,
      key: "PROJ-2",
      url: "https://jira.example.com/browse/PROJ-2",
    };
    const body = buildPrBody([baseTicket, ticket2]);
    expect(body).toContain("[PROJ-1]");
    expect(body).toContain("[PROJ-2]");
  });

  test("includes the auto-generated footer", () => {
    const body = buildPrBody([baseTicket]);
    expect(body).toContain("Auto-generated by TicketSync");
  });
});
