import { Resend } from "resend";
import { config } from "./config.ts";
import type { JiraTicket } from "./jira.ts";

const resend = new Resend(config.RESEND_API_KEY);

export async function sendDoneNotification(
  tickets: JiraTicket[],
  prUrl: string
): Promise<void> {
  const recipients = config.EMAIL_TO.split(",").map((e) => e.trim());
  const subject =
    tickets.length === 1
      ? `[TicketSync] ${tickets[0]!.key} moved to Done`
      : `[TicketSync] ${tickets.length} tickets moved to Done`;

  const html = buildHtml(tickets, prUrl);

  const { error } = await resend.emails.send({
    from: config.EMAIL_FROM,
    to: recipients,
    subject,
    html,
  });

  if (error) {
    throw new Error(`Resend error: ${JSON.stringify(error)}`);
  }

  console.log(`    Resend email sent to ${recipients.join(", ")}`);
}

function buildHtml(tickets: JiraTicket[], prUrl: string): string {
  const rows = tickets
    .map(
      (t) => `
      <tr>
        <td><a href="${t.url}">${t.key}</a></td>
        <td>${t.summary}</td>
        <td>${t.issueType}</td>
        <td>${t.priority}</td>
        <td>${t.assignee}</td>
        <td>${t.sprint}</td>
        <td>${t.resolutionDate}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; color: #333; }
    h2 { color: #0052CC; }
    table { border-collapse: collapse; width: 100%; }
    th { background: #0052CC; color: white; padding: 8px 12px; text-align: left; }
    td { padding: 8px 12px; border-bottom: 1px solid #ddd; }
    tr:hover { background: #f5f5f5; }
    a { color: #0052CC; }
    .btn { display:inline-block; margin-top:16px; padding:10px 20px; background:#0052CC; color:white; border-radius:4px; text-decoration:none; }
    .footer { margin-top:24px; font-size:12px; color:#888; }
  </style>
</head>
<body>
  <h2>Tickets Moved to Done</h2>
  <p>${tickets.length} ticket(s) were moved to <strong>Done</strong> status.</p>
  <table>
    <thead>
      <tr>
        <th>Key</th>
        <th>Summary</th>
        <th>Type</th>
        <th>Priority</th>
        <th>Assignee</th>
        <th>Sprint</th>
        <th>Resolution Date</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <a class="btn" href="${prUrl}">View GitHub PR</a>
  <p class="footer">Auto-generated by TicketSync &bull; ${new Date().toUTCString()}</p>
</body>
</html>`;
}
