import { config } from "./config.ts";
import type { JiraTicket } from "./jira.ts";

const BASE = "https://api.github.com";

async function ghFetch(
  path: string,
  method: string = "GET",
  body?: unknown
): Promise<unknown> {
  const res = await fetch(`${BASE}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${config.GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API error ${res.status} for ${method} ${path}: ${text}`);
  }

  // 204 No Content
  if (res.status === 204) return null;
  return res.json();
}

async function getBaseBranchSha(): Promise<string> {
  const data = (await ghFetch(
    `/repos/${config.GITHUB_OWNER}/${config.GITHUB_REPO}/git/ref/heads/${config.GITHUB_BASE_BRANCH}`
  )) as { object: { sha: string } };
  return data.object.sha;
}

async function getFileSha(): Promise<{ sha: string; content: string } | null> {
  try {
    const data = (await ghFetch(
      `/repos/${config.GITHUB_OWNER}/${config.GITHUB_REPO}/contents/${config.GITHUB_CSV_PATH}?ref=${config.GITHUB_BASE_BRANCH}`
    )) as { sha: string; content: string };
    return { sha: data.sha, content: atob(data.content.replace(/\n/g, "")) };
  } catch {
    return null;
  }
}

async function createBranch(branchName: string, sha: string): Promise<void> {
  await ghFetch(`/repos/${config.GITHUB_OWNER}/${config.GITHUB_REPO}/git/refs`, "POST", {
    ref: `refs/heads/${branchName}`,
    sha,
  });
}

async function upsertFile(
  branchName: string,
  content: string,
  commitMessage: string,
  fileSha?: string
): Promise<void> {
  const body: Record<string, unknown> = {
    message: commitMessage,
    content: btoa(unescape(encodeURIComponent(content))),
    branch: branchName,
  };
  if (fileSha) body["sha"] = fileSha;

  await ghFetch(
    `/repos/${config.GITHUB_OWNER}/${config.GITHUB_REPO}/contents/${config.GITHUB_CSV_PATH}`,
    "PUT",
    body
  );
}

async function createPullRequest(
  branchName: string,
  title: string,
  body: string
): Promise<string> {
  const data = (await ghFetch(
    `/repos/${config.GITHUB_OWNER}/${config.GITHUB_REPO}/pulls`,
    "POST",
    {
      title,
      body,
      head: branchName,
      base: config.GITHUB_BASE_BRANCH,
    }
  )) as { html_url: string };
  return data.html_url;
}

export async function createTicketPR(
  tickets: JiraTicket[],
  updatedCsvContent: string
): Promise<string> {
  const ticketKeys = tickets.map((t) => t.key).join(", ");
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const branchName = `ticketsync/done-${timestamp}`;

  const baseSha = await getBaseBranchSha();
  const existing = await getFileSha();

  await createBranch(branchName, baseSha);

  const commitMsg = `[TicketSync] Mark ${ticketKeys} as Done`;
  await upsertFile(branchName, updatedCsvContent, commitMsg, existing?.sha);

  const prBody = buildPrBody(tickets);
  const prTitle =
    tickets.length === 1
      ? `[TicketSync] ${tickets[0]!.key} moved to Done`
      : `[TicketSync] ${tickets.length} tickets moved to Done`;

  const prUrl = await createPullRequest(branchName, prTitle, prBody);
  return prUrl;
}

function buildPrBody(tickets: JiraTicket[]): string {
  const rows = tickets
    .map(
      (t) =>
        `| [${t.key}](${t.url}) | ${t.summary} | ${t.issueType} | ${t.priority} | ${t.assignee} | ${t.resolutionDate} |`
    )
    .join("\n");

  return `## Tickets Moved to Done

| Key | Summary | Type | Priority | Assignee | Resolution Date |
|-----|---------|------|----------|----------|-----------------|
${rows}

---
*Auto-generated by TicketSync on ${new Date().toUTCString()}*`;
}
